name: mmwave
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.2=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
    - anyio==4.11.0
    - argon2-cffi==25.1.0
    - argon2-cffi-bindings==25.1.0
    - arrow==1.4.0
    - asttokens==3.0.0
    - attrs==25.4.0
    - beautifulsoup4==4.14.2
    - bleach==6.3.0
    - cffi==2.0.0
    - comm==0.2.3
    - contourpy==1.3.2
    - cycler==0.12.1
    - debugpy==1.8.17
    - decorator==5.2.1
    - defusedxml==0.7.1
    - einops==0.8.1
    - exceptiongroup==1.3.0
    - executing==2.2.1
    - fastjsonschema==2.21.2
    - filelock==3.13.1
    - fonttools==4.59.1
    - fqdn==1.5.1
    - freetype-py==2.5.1
    - fsspec==2024.6.1
    - idna==3.11
    - imageio==2.37.0
    - ipykernel==7.1.0
    - ipython==8.37.0
    - isoduration==20.11.0
    - jedi==0.19.2
    - jinja2==3.1.4
    - joblib==1.5.1
    - jsonpointer==3.0.0
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - jupyter-client==8.6.3
    - jupyter-core==5.9.1
    - jupyter-events==0.12.0
    - jupyter-server==2.17.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab-pygments==0.3.0
    - kiwisolver==1.4.9
    - lark==1.3.1
    - lmdb==1.7.3
    - markupsafe==2.1.5
    - matplotlib==3.10.5
    - matplotlib-inline==0.2.1
    - mistune==3.1.4
    - mpmath==1.3.0
    - msgpack==1.1.1
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.3
    - numpy==2.2.6
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-nccl-cu11==2.21.5
    - nvidia-nvtx-cu11==11.8.86
    - opencv-python==4.12.0.88
    - overrides==7.7.0
    - packaging==25.0
    - pandas==2.3.3
    - pandocfilters==1.5.1
    - parso==0.8.5
    - pexpect==4.9.0
    - pillow==11.0.0
    - platformdirs==4.5.0
    - pointnet2-ops==3.0.0
    - prometheus-client==0.23.1
    - prompt-toolkit==3.0.52
    - psutil==7.1.2
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pycparser==2.23
    - pyglet==2.1.8
    - pygments==2.19.2
    - pymanopt==2.2.1
    - pyopengl==3.1.0
    - pyparsing==3.2.3
    - pyrender==0.1.45
    - python-dateutil==2.9.0.post0
    - python-json-logger==4.0.0
    - pytz==2025.2
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - referencing==0.37.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rfc3987-syntax==1.1.0
    - rpds-py==0.28.0
    - scikit-learn==1.7.1
    - scipy==1.15.3
    - send2trash==1.8.3
    - six==1.17.0
    - smplx==0.1.28
    - sniffio==1.3.1
    - soupsieve==2.8
    - stack-data==0.6.3
    - sympy==1.13.3
    - terminado==0.18.1
    - threadpoolctl==3.6.0
    - tinycss2==1.4.0
    - torch==2.7.1+cu118
    - torchaudio==2.7.1+cu118
    - torchvision==0.22.1+cu118
    - tornado==6.5.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - trimesh==4.7.4
    - triton==3.3.1
    - typing-extensions==4.12.2
    - tzdata==2025.2
    - uri-template==1.3.0
    - wcwidth==0.2.14
    - webcolors==25.10.0
    - webencodings==0.5.1
    - websocket-client==1.9.0
prefix: /home/user/anaconda3/envs/mmwave
